Task 1 :-
1.	Write a query to retrieve all records from the Customers table..
2.	Write a query to retrieve the names and email addresses of customers whose names start with 'J'.
3.	Write a query to retrieve the order details (OrderID, ProductName, Quantity) for all orders..
4.	Write a query to calculate the total quantity of products ordered.
5.	Write a query to retrieve the names of customers who have placed an order.
6.	Write a query to retrieve the products with a price greater than $10.00.
7.	Write a query to retrieve the customer name and order date for all orders placed on or after '2023-07-05'.
8.	Write a query to calculate the average price of all products.
9.	Write a query to retrieve the customer names along with the total quantity of products they have ordered.
10.	Write a query to retrieve the products that have not been ordered.

SOLUTION:-

1)select * from customers;

2)select Name,Email from customers where Name LIKE 'J%';

3)SELECT OrderID,ProductName,Quantity FROM Orders;

4)select count(ProductID) AS TotalQuantity from products;

5)select C.Name from Customers C
INNER JOIN Orders O
ON C.CustomerID=O.CustomerID;

6)select ProductName,Price from Products where Price>10.00;

7)select C.Name,O.OrderDate from Customers C
INNER JOIN Orders O
ON C.CustomerID=O.CustomerID
Where OrderDate>='2023-07-05';

8)select AVG(Price) as Average_Price from Products;

9)select C.Name,O.Quantity from Customers C
INNER JOIN Orders O
ON C.CustomerID=O.CustomerID

10)select P.ProductName from Products P
INNER JOIN Orders O
ON P.ProductID=O.CustomerID
WHERE P.ProductName !=O.ProductName


Task 2 :-
1.	Write a query to retrieve the top 5 customers who have placed the highest total quantity of orders.
2.	Write a query to calculate the average price of products for each product category.
3.	Write a query to retrieve the customers who have not placed any orders.
4.	Write a query to retrieve the order details (OrderID, ProductName, Quantity) for orders placed by customers whose names start with 'M'.
5.	Write a query to calculate the total revenue generated from all orders.
6.	Write a query to retrieve the customer names along with the total revenue generated from their orders.
7.	Write a query to retrieve the customers who have placed at least one order for each product category.
8.	Write a query to retrieve the customers who have placed orders on consecutive days.
9.	Write a query to retrieve the top 3 products with the highest average quantity ordered.
10.	Write a query to calculate the percentage of orders that have a quantity greater than the average quantity.


SOLUTION:-

1)select TOP 5 C.Name,O.Quantity from Customers C
INNER JOIN Orders O
ON C.CustomerID=O.CustomerID
order by O.quantity DESC;

2)select ProductName,AVG(Price) as Average_Price from Products
GROUP BY ProductName;

3)select C.Name from Customers C 
INNER JOIN Orders O
ON C.CustomerID=O.CustomerID
where O.CustomerID <> C.CustomerID;

4)select O.OrderID,O.ProductName,O.Quantity from Customers C
INNER JOIN Orders O
ON C.CustomerID=O.CustomerID
where C.Name LIKE 'M%';

5)select SUM(Price) as Total_Revenue from Products;

6)

8)

9)select TOP 3 * from orders 
where Quantity>
(select avg(Quantity) from orders)


10)select COUNT(*) from orders
   where Quantity>
   (select avg(Quantity) from orders)


Task 3:-
1.	Write a query to retrieve the customers who have placed orders for all products.
2.	Write a query to retrieve the products that have been ordered by all customers.
3.	Write a query to calculate the total revenue generated from orders placed in each month.
4.	Write a query to retrieve the products that have been ordered by more than 50% of the customers.
5.	Write a query to retrieve the customers who have placed orders for all products in a specific category.
6.	Write a query to retrieve the top 5 customers who have spent the highest amount of money on orders.
7.	Write a query to calculate the running total of order quantities for each customer.
8.	Write a query to retrieve the top 3 most recent orders for each customer.
9.	Write a query to calculate the total revenue generated by each customer in the last 30 days.
10.	Write a query to retrieve the customers who have placed orders for at least two different product categories.
11.	Write a query to calculate the average revenue per order for each customer.
12.	Write a query to retrieve the products that have been ordered by customers from a specific country.
13.	Write a query to retrieve the customers who have placed orders for every month of a specific year.
14.	Write a query to retrieve the customers who have placed orders for a specific product in consecutive months.
15.	Write a query to retrieve the products that have been ordered by a specific customer at least twice.

solution:-

1)
